JobPortal/config/routes.rb
Rails.application.routes.draw do

  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy' 

  get     'register'    => 'users#new', as: :new_user
  get     'change-password' => 'users#change_password', as: :change_password
  resources :users

  get     'available-jobs'  => 'jobs#available_jobs', as: :available_jobs
  resources :jobs

  post    'apply-job/:job_id'       => 'job_applications#apply', as: :apply_job

  get     '/:page'      => 'pages#show'
  root    'pages#show', page: 'home'
end

JobPortal/app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many   :job_application
end

JobPortal/app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  belongs_to    :job
  belongs_to    :user
end

JobPortal/app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }, allow_blank: true
end

JobPortal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

JobPortal/app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController

  def apply
    job = Job.find_by(id: params[:job_id])
    @job_application = JobApplication.create(user: current_user, job: job)
    if @job_application.save
      flash[:success] = "Application successful!"
      redirect_to jobs_url
    else
      redirect_to available_jobs_url
    end
  end

  private
    def job_application_params
      params.require(:user)
      params.require(:job)
    end
end

JobPortal/app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.where(user_id: current_user.id)
    @job_applications = JobApplication.where(user_id: current_user.id)
  end

  def available_jobs
    if logged_in?
      @jobs = Job.where(active: true)
    else
      @jobs = Job.where('active = ?', true)
    end
  end

  def new
    @job = Job.new    
  end

  def create
    @job = Job.create(job_params)
    @job.user_id = current_user.id
    if @job.save
      flash[:success] = "#{@job.job_title} created."
      redirect_to jobs_url
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
    if @job.user_id != current_user.id
      redirect_to jobs_url
    end
  end
  
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "#{@job.job_title} updated."
      redirect_to jobs_url
    else
      render 'edit'
    end
  end

  def destroy
    Job.find(params[:id]).destroy
    flash[:success] = "Job posting deleted."
    redirect_to jobs_url
  end

  private
    def job_params
      params.require(:job).permit(:job_title, :minimum_salary, :maximum_salary, :description, :active)
    end


end

JobPortal/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
    end

end

JobPortal/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash.now[:success] = "Successful login."
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email address/password"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end

end

JobPortal/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :show]

  def index
  end

  def show
    @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render file: 'public/404.html', status: :not_found
  end

  def new
    @user = User.new    
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Rails Job Portal"
      redirect_to(root_url)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
  end

  def change_password
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url 
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

JobPortal/app/helpers/application_helper.rb
module ApplicationHelper
end

JobPortal/app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

JobPortal/app/helpers/jobs_helper.rb
module JobsHelper
end

JobPortal/app/helpers/pages_helper.rb
module PagesHelper
end

JobPortal/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

JobPortal/app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.email, class: "gravatar")
    end

end

JobPortal/app/views/jobs/available_jobs.html.erb
<% provide(:title, "Jobs") %>

<div class="row"><div class="col-md-6 col-md-offset-3">
  <h1>Available Jobs</h1>

  <div class="row">
    <% @jobs.each do |job| %>
      <% if job.user_id != current_user.id %>
        <div class="col-sm-12">
          <div class="thumbnail">
            <div class="caption">
              <h4><%= job.job_title %></h4>
              <p><%= job.description %></p>
              <p><strong>Salary range: </strong> <%= job.minimum_salary %> to <%= job.maximum_salary %></p>
              <p><%= link_to "Apply", apply_job_path(job_id: job.id), method: :post, :class => "btn btn-success" %></p> 
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div></div>

JobPortal/app/views/jobs/edit.html.erb
<% provide(:title, "Create Job") %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>Edit Job</h2>
    <%= form_for(@job, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render "shared/jobs/error_messages" %>

      <div class="form-group">
        <%= f.label :job_title %>
        <%= f.text_field :job_title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :minimum_salary %>
        <%= f.number_field :minimum_salary, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :maximum_salary %>
        <%= f.number_field :maximum_salary, :class => "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :active, "Status" %>
        <%= f.select :active, [["Active", true], ["Inactive", false]], {}, :class => "form-control" %>
      </div>    
  

      <%= f.submit "Update", :class => "btn btn-primary" %>
      <%= link_to "Cancel", jobs_path, :class => "btn btn-default" %>
    <% end %>

  </div>
</div>

JobPortal/app/views/jobs/index.html.erb
<% provide(:title, "Jobs") %>

<div class="row">
  <div class="col-md-6">
    <h1>My Job Listing</h1>

    <div class="row">
      <% @jobs.each do |job| %>
      <div class="col-sm-12">
        <div class="thumbnail">
          <div class="caption">
            <h4><%= job.job_title %></h4>
            <p><%= job.description %></p>
            <p><strong>Salary range:</strong> <%= job.minimum_salary %> to <%= job.maximum_salary %></p>
            <p>
              <%= link_to "Edit", edit_job_path(job), :class => "btn btn-info" %>
              <%= link_to "Delete", job, method: :delete, data: { confirm: "Are you sure?"}, :class => "btn btn-danger" %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <h1>Pending Applications</h1>

    <div class="row">
      <% @job_applications.each do |app| %>
      <div class="col-sm-12">
        <div class="thumbnail">
          <div class="caption">
            <h4><%= app.job.job_title %></h4>
            <p><%= app.job.description %></p>
            <p><strong>Salary range: </strong><%= app.job.minimum_salary %> to <%= app.job.maximum_salary %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

JobPortal/app/views/jobs/new.html.erb
<% provide(:title, "Create Job") %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>Create Job</h2>
    <%= form_for(@job, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render "shared/jobs/error_messages" %>

      <div class="form-group">
        <%= f.label :job_title %>
        <%= f.text_field :job_title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :minimum_salary %>
        <%= f.text_field :minimum_salary, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :maximum_salary %>
        <%= f.text_field :maximum_salary, :class => "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :active, "Status" %>
        <%= f.select :active, [["Active", true], ["Inactive", false]], {}, :class => "form-control" %>
      </div>    
  

      <%= f.submit "Add", :class => "btn btn-primary" %>
      <%= link_to "Cancel", jobs_path, :class => "btn btn-default" %>
    <% end %>

  </div>
</div>

JobPortal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Portal</title>

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= yield :head %>
  <%= yield :css %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/nav" %>

  <div class="container">
    
    <%= render "shared/flash_messages" %>

    <%= yield %>
  </div>

  <%= render "shared/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= yield :javascript %>
  <div class="container">
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

JobPortal/app/views/pages/home.html.erb
<h1>Welcome to Rails Job Portal</h1>

JobPortal/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

JobPortal/app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

JobPortal/app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Powered by Ruby on Rails.</p>
  </div>
</footer>

JobPortal/app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rails Job Portal</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">                                                                                                                        
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", "/about" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Jobs <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
            <li><%= link_to "My Jobs", jobs_path %></li>
            <li><%= link_to "Create Job", new_job_path %></li>
            <li class="divider"></li>
            <% end %>
            <li><%= link_to "Available Jobs", available_jobs_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if !logged_in? %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Register", new_user_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Change Password", change_password_path %></li>
            </ul> 
          </li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

JobPortal/app/views/shared/jobs/_error_messages.html.erb
<% if @job.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@job.errors.count, "error") %>.
    </div>
    <ul>
      <% @job.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

JobPortal/app/views/users/change_password.html.erb
<% provide(:title, "Change Password") %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>Change Password</h2>
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render "shared/error_messages" %>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>

      <%= f.submit "Update Password", :class => "btn btn-primary" %>
      <%= link_to "Back to Profile", current_user, :class => "btn btn-default" %>
    <% end %>
  </div>
</div>

JobPortal/app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>Edit Account</h2>
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render "shared/error_messages" %>

      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>
      </div>

      <%= f.submit "Update", :class => "btn btn-primary" %>

    <% end %>
  </div>
</div>

JobPortal/app/views/users/index.html.erb
<h1>List of all Users</h1>

JobPortal/app/views/users/new.html.erb
<% provide(:title, "Register") %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h2>Register User</h2>
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render "shared/error_messages" %>

      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>

      <%= f.submit "Register", :class => "btn btn-block btn-primary" %>

    <% end %>
    <p>Already have an account? <%= link_to "Login here", login_path %></p>
  </div>
</div>

JobPortal/app/views/users/show.html.erb
<% provide(:title, @user.email) %>

<h1>Hello, <%= @user.first_name %> <%= @user.last_name %></h1>
<%= gravatar_for @user %>